name: zing
description: Adds a zing to your application.
version: 0.0.0
repository: https://github.com/ArishSultan/zing.git

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
